---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__(<p>__start__</p>)
	bank_step(bank_step)
	regulatory_step(regulatory_step)
	auditor_step(auditor_step)
	analyst_step(analyst_step)
	coordination_step(coordination_step)
	synthesis(synthesis)
	tools(tools)
	__end__(<p>__end__</p>)
	__start__ -.-> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
