[project]
name = "ceclagents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "dotenv>=0.9.9",
  "langchain-anthropic>=0.3.15",
  "langchain-core>=0.3.64",
  "langchain-openai>=0.3.21",
  "langgraph>=0.4.8",
]
